// <auto-generated />
using System;
using ErasmusAtlas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace ErasmusAtlas.Infrastructure.Migrations
{
    [DbContext(typeof(ErasmusAtlasDbContext))]
    [Migration("20260414143510_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryIso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryIso2 = "ES",
                            Latitude = 40.416800000000002,
                            Longitude = -3.7038000000000002,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 2,
                            CountryIso2 = "ES",
                            Latitude = 41.385100000000001,
                            Longitude = 2.1734,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 3,
                            CountryIso2 = "ES",
                            Latitude = 39.469900000000003,
                            Longitude = -0.37630000000000002,
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 4,
                            CountryIso2 = "ES",
                            Latitude = 37.389099999999999,
                            Longitude = -5.9844999999999997,
                            Name = "Seville"
                        },
                        new
                        {
                            Id = 5,
                            CountryIso2 = "IT",
                            Latitude = 41.902799999999999,
                            Longitude = 12.4964,
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 6,
                            CountryIso2 = "IT",
                            Latitude = 45.464199999999998,
                            Longitude = 9.1899999999999995,
                            Name = "Milan"
                        },
                        new
                        {
                            Id = 7,
                            CountryIso2 = "IT",
                            Latitude = 44.494900000000001,
                            Longitude = 11.342599999999999,
                            Name = "Bologna"
                        },
                        new
                        {
                            Id = 8,
                            CountryIso2 = "IT",
                            Latitude = 43.769599999999997,
                            Longitude = 11.255800000000001,
                            Name = "Florence"
                        },
                        new
                        {
                            Id = 9,
                            CountryIso2 = "FR",
                            Latitude = 48.8566,
                            Longitude = 2.3521999999999998,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 10,
                            CountryIso2 = "FR",
                            Latitude = 45.764000000000003,
                            Longitude = 4.8357000000000001,
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = 11,
                            CountryIso2 = "FR",
                            Latitude = 44.837800000000001,
                            Longitude = -0.57920000000000005,
                            Name = "Bordeaux"
                        },
                        new
                        {
                            Id = 12,
                            CountryIso2 = "FR",
                            Latitude = 43.604700000000001,
                            Longitude = 1.4441999999999999,
                            Name = "Toulouse"
                        },
                        new
                        {
                            Id = 13,
                            CountryIso2 = "DE",
                            Latitude = 52.520000000000003,
                            Longitude = 13.404999999999999,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 14,
                            CountryIso2 = "DE",
                            Latitude = 48.135100000000001,
                            Longitude = 11.582000000000001,
                            Name = "Munich"
                        },
                        new
                        {
                            Id = 15,
                            CountryIso2 = "DE",
                            Latitude = 53.551099999999998,
                            Longitude = 9.9937000000000005,
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = 16,
                            CountryIso2 = "DE",
                            Latitude = 49.398800000000001,
                            Longitude = 8.6723999999999997,
                            Name = "Heidelberg"
                        },
                        new
                        {
                            Id = 17,
                            CountryIso2 = "PT",
                            Latitude = 38.722299999999997,
                            Longitude = -9.1393000000000004,
                            Name = "Lisbon"
                        },
                        new
                        {
                            Id = 18,
                            CountryIso2 = "PT",
                            Latitude = 41.157899999999998,
                            Longitude = -8.6290999999999993,
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 19,
                            CountryIso2 = "PT",
                            Latitude = 40.203299999999999,
                            Longitude = -8.4102999999999994,
                            Name = "Coimbra"
                        },
                        new
                        {
                            Id = 20,
                            CountryIso2 = "PT",
                            Latitude = 41.545400000000001,
                            Longitude = -8.4265000000000008,
                            Name = "Braga"
                        },
                        new
                        {
                            Id = 21,
                            CountryIso2 = "NL",
                            Latitude = 52.367600000000003,
                            Longitude = 4.9040999999999997,
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = 22,
                            CountryIso2 = "NL",
                            Latitude = 52.090699999999998,
                            Longitude = 5.1214000000000004,
                            Name = "Utrecht"
                        },
                        new
                        {
                            Id = 23,
                            CountryIso2 = "NL",
                            Latitude = 53.2194,
                            Longitude = 6.5664999999999996,
                            Name = "Groningen"
                        },
                        new
                        {
                            Id = 24,
                            CountryIso2 = "NL",
                            Latitude = 52.1601,
                            Longitude = 4.4969999999999999,
                            Name = "Leiden"
                        },
                        new
                        {
                            Id = 25,
                            CountryIso2 = "PL",
                            Latitude = 52.229700000000001,
                            Longitude = 21.0122,
                            Name = "Warsaw"
                        },
                        new
                        {
                            Id = 26,
                            CountryIso2 = "PL",
                            Latitude = 50.064700000000002,
                            Longitude = 19.945,
                            Name = "Kraków"
                        },
                        new
                        {
                            Id = 27,
                            CountryIso2 = "PL",
                            Latitude = 54.351999999999997,
                            Longitude = 18.646599999999999,
                            Name = "Gdańsk"
                        },
                        new
                        {
                            Id = 28,
                            CountryIso2 = "PL",
                            Latitude = 51.107900000000001,
                            Longitude = 17.038499999999999,
                            Name = "Wrocław"
                        },
                        new
                        {
                            Id = 29,
                            CountryIso2 = "CZ",
                            Latitude = 50.075499999999998,
                            Longitude = 14.437799999999999,
                            Name = "Prague"
                        },
                        new
                        {
                            Id = 30,
                            CountryIso2 = "CZ",
                            Latitude = 49.195099999999996,
                            Longitude = 16.6068,
                            Name = "Brno"
                        },
                        new
                        {
                            Id = 31,
                            CountryIso2 = "CZ",
                            Latitude = 49.593800000000002,
                            Longitude = 17.250900000000001,
                            Name = "Olomouc"
                        },
                        new
                        {
                            Id = 32,
                            CountryIso2 = "CZ",
                            Latitude = 49.738399999999999,
                            Longitude = 13.3736,
                            Name = "Plzeň"
                        },
                        new
                        {
                            Id = 33,
                            CountryIso2 = "SE",
                            Latitude = 59.329300000000003,
                            Longitude = 18.0686,
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = 34,
                            CountryIso2 = "SE",
                            Latitude = 57.7089,
                            Longitude = 11.974600000000001,
                            Name = "Gothenburg"
                        },
                        new
                        {
                            Id = 35,
                            CountryIso2 = "SE",
                            Latitude = 55.704700000000003,
                            Longitude = 13.191000000000001,
                            Name = "Lund"
                        },
                        new
                        {
                            Id = 36,
                            CountryIso2 = "SE",
                            Latitude = 59.858600000000003,
                            Longitude = 17.6389,
                            Name = "Uppsala"
                        },
                        new
                        {
                            Id = 37,
                            CountryIso2 = "GR",
                            Latitude = 37.983800000000002,
                            Longitude = 23.727499999999999,
                            Name = "Athens"
                        },
                        new
                        {
                            Id = 38,
                            CountryIso2 = "GR",
                            Latitude = 40.640099999999997,
                            Longitude = 22.944400000000002,
                            Name = "Thessaloniki"
                        },
                        new
                        {
                            Id = 39,
                            CountryIso2 = "GR",
                            Latitude = 38.246600000000001,
                            Longitude = 21.7346,
                            Name = "Patras"
                        },
                        new
                        {
                            Id = 40,
                            CountryIso2 = "GR",
                            Latitude = 35.338700000000003,
                            Longitude = 25.144200000000001,
                            Name = "Heraklion"
                        });
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.ErasmusUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.PostTopic", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("PostTopics");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.ProjectApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivation")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectApplications");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.ProjectTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTags");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Praktika"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Erasmus+ Exchange"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Erasmus Course"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Volunteering"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Research / Lab"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Summer School"
                        });
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.SavedPost", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErasmusUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("PostId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("ErasmusUserId");

                    b.HasIndex("PostId");

                    b.HasIndex("PostId1");

                    b.ToTable("SavedPosts");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.SavedProject", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErasmusUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ProjectId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ErasmusUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId1");

                    b.ToTable("SavedProjects");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Business"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Design"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Law"
                        });
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nightlife"
                        },
                        new
                        {
                            Id = 5,
                            Name = "University"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Internship"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Warning"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Recommendation"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Culture"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Costs"
                        },
                        new
                        {
                            Id = 11,
                            Name = "General"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Travel"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Institution", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Post", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.PostTopic", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Post", "Post")
                        .WithMany("PostTopics")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Topic", "Topic")
                        .WithMany("PostTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Project", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId");

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Institution");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.ProjectApplication", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.ProjectTag", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Project", "Project")
                        .WithMany("ProjectTags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Tag", "Tag")
                        .WithMany("ProjectTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.SavedPost", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", null)
                        .WithMany("SavedPosts")
                        .HasForeignKey("ErasmusUserId");

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Post", null)
                        .WithMany("SavedByUsers")
                        .HasForeignKey("PostId1");

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.SavedProject", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", null)
                        .WithMany("SavedProjects")
                        .HasForeignKey("ErasmusUserId");

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.Project", null)
                        .WithMany("SavedByUsers")
                        .HasForeignKey("ProjectId1");

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ErasmusAtlas.Infrastructure.Models.ErasmusUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.ErasmusUser", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("SavedPosts");

                    b.Navigation("SavedProjects");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Post", b =>
                {
                    b.Navigation("PostTopics");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Project", b =>
                {
                    b.Navigation("ProjectTags");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Tag", b =>
                {
                    b.Navigation("ProjectTags");
                });

            modelBuilder.Entity("ErasmusAtlas.Infrastructure.Models.Topic", b =>
                {
                    b.Navigation("PostTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
